//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Symlconnect.Maternity.Common.UnitTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Symlconnect.Maternity.Common.UnitTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;datadictionary name=&quot;maternity&quot;&gt;
        ///  &lt;properties&gt;
        ///    &lt;!-- These are common properties that can be referenced from several entities --&gt;
        ///    &lt;property name=&quot;Name&quot; kind=&quot;Text&quot;/&gt;
        ///    &lt;property name=&quot;AddressLine1&quot; kind=&quot;Text&quot;/&gt;
        ///    &lt;property name=&quot;AddressLine2&quot; kind=&quot;Text&quot;/&gt;
        ///    &lt;property name=&quot;AddressLine3&quot; kind=&quot;Text&quot;/&gt;
        ///    &lt;property name=&quot;PostCode&quot; kind=&quot;Text&quot;/&gt;
        ///    &lt;property name=&quot;Telephone&quot; kind=&quot;Text&quot; validation=&quot;telephone-number&quot;/&gt;
        ///  &lt;/properties&gt;
        ///  &lt;enti [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string maternity_datadictionary {
            get {
                return ResourceManager.GetString("maternity_datadictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;formdefinition&gt;
        ///  
        ///&lt;/formdefinition&gt;.
        /// </summary>
        internal static string maternity_formdefinition {
            get {
                return ResourceManager.GetString("maternity_formdefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;entity id=&quot;2dd7006e-81bc-4def-8ab8-57b3524d1422-1&quot; datadictionary=&quot;maternity&quot; entityname=&quot;record&quot; createddatetime=&quot;2017-01-02T00:00:00.0000000Z&quot; createdbyuserid=&quot;CreatedByUserIdValue&quot; createdbyuserdisplayname=&quot;CreatedByUserDisplayNameValue&quot;&gt;
        ///  &lt;values propertyname=&quot;Name&quot;&gt;
        ///    &lt;value sessionid=&quot;Session1&quot; userid=&quot;UserId1&quot; changedatetime=&quot;2017-01-01T00:00:00.0000000Z&quot;&gt;John Doe&lt;/value&gt;
        ///  &lt;/values&gt;
        ///  &lt;values propertyname=&quot;LikesToBeCalled&quot;&gt;
        ///    &lt;value sessionid=&quot;Sess [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string maternity_record {
            get {
                return ResourceManager.GetString("maternity_record", resourceCulture);
            }
        }
    }
}
