//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Symlconnect.DataModel.UnitTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Symlconnect.DataModel.UnitTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;datadictionary name=&quot;datadictionaryname&quot;&gt;
        ///    &lt;properties&gt;
        ///        &lt;property name=&quot;sharedtextproperty1&quot; kind=&quot;Text&quot;/&gt;
        ///        &lt;property name=&quot;sharednumericproperty1&quot; kind=&quot;Numeric&quot;/&gt;
        ///        &lt;property name=&quot;sharedintegerproperty1&quot; kind=&quot;Integer&quot;/&gt;
        ///        &lt;property name=&quot;sharedbooleanproperty1&quot; kind=&quot;Boolean&quot;/&gt;
        ///        &lt;property name=&quot;shareddatetimeproperty1&quot; kind=&quot;DateTime&quot;/&gt;
        ///    &lt;/properties&gt;
        ///    &lt;entitydefinitions&gt;
        ///        &lt;entitydefinition name=&quot;entity1&quot;&gt;
        ///            &lt;properties&gt;
        ///            [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DataDictionaryXml {
            get {
                return ResourceManager.GetString("DataDictionaryXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;entity datadictionary=&quot;DataDictionaryName&quot; entityname=&quot;EntityName&quot;&gt;
        ///  &lt;values propertyname=&quot;stringproperty&quot;&gt;
        ///    &lt;value sessionid=&quot;SessionIdValue0&quot; userid=&quot;UserIdValue0&quot; changedatetime=&quot;2017-01-01T00:00:00.0000000Z&quot;&gt;StringValue1&lt;/value&gt;
        ///    &lt;value sessionid=&quot;SessionIdValue1&quot; userid=&quot;UserIdValue1&quot; changedatetime=&quot;2017-01-02T00:00:00.0000000Z&quot;&gt;StringValue2&lt;/value&gt;
        ///    &lt;value sessionid=&quot;SessionIdValue2&quot; userid=&quot;UserIdValue2&quot; changedatetime=&quot;2017-01-03T00:00:00.0000000Z&quot;&gt;StringValue3&lt;/value&gt;
        ///  &lt;/values&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string entity_basic {
            get {
                return ResourceManager.GetString("entity_basic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;entity datadictionary=&quot;DataDictionaryName&quot; entityname=&quot;EntityName&quot;&gt;
        ///  &lt;childentities propertyname=&quot;ChildEntitiesPropertyName&quot;&gt;
        ///    &lt;childentity sessionid=&quot;SessionIdValue&quot; userid=&quot;UserIdValue&quot; createddatetime=&quot;2017-01-01T00:00:00.0000000Z&quot;&gt;
        ///      &lt;entity datadictionary=&quot;DataDictionaryName&quot; entity=&quot;ChildEntityName&quot;&gt;
        ///        &lt;values propertyname=&quot;stringproperty&quot;&gt;
        ///          &lt;value sessionid=&quot;SessionIdValue0&quot; userid=&quot;UserIdValue0&quot; changedatetime=&quot;2017-01-01T00:00:00.0000000Z&quot;&gt;StringValue1&lt;/value&gt;
        ///         [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string entity_childentities {
            get {
                return ResourceManager.GetString("entity_childentities", resourceCulture);
            }
        }
    }
}
